targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/data/models/*.dart
          - lib/presentation/viewmodels/*.dart
        options:
          build_extensions:
            "lib/data/models/{{file}}.dart":
              - "lib/generated/models/{{file}}.freezed.dart"
            "lib/presentation/viewmodels/{{file}}.dart":
              - "lib/generated/viewmodels/{{file}}.freezed.dart"
      json_serializable:
        generate_for:
          - lib/data/models/*.dart
        options:
          build_extensions:
            "lib/data/models/{{file}}.dart":
              - "lib/generated/models/{{file}}.g.dart"
      retrofit_generator:
        generate_for:
          - lib/data/api/*.dart
        options:
          build_extensions:
            "lib/data/api/{{file}}.dart":
              - "lib/generated/api/{{file}}.g.dart"
      riverpod_generator:
        generate_for:
          - lib/presentation/viewmodels/*.dart
          - lib/presentation/providers/*.dart
        options:
          build_extensions:
            "lib/presentation/viewmodels/{{file}}.dart":
              - "lib/generated/viewmodels/{{file}}.g.dart"
            "lib/presentation/providers/{{file}}.dart":
              - "lib/generated/providers/{{file}}.g.dart"
